### PR TITLE
Lint + Default values + 2 new checks

### PR DESCRIPTION
**Pull request by magnuslarsen**
First of, apologies for the huge PR :-) 

I ran all the scripts through [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer), and made everything identical. This makes it a lot easier to maintain (or just to create new checks).
I've made no breaking changes. Everything outputs and inputs the same as before. Verified using PowerShell 5.

I also added defaults to `-Warning` and `-Critical` based on default on the equivalent Ruby scripts (from sensu-plugins)

For all `metric-` checks, I've added a new paramter `-Scheme`. This is the same as on all Ruby based scripts. I've left `-UseFullyQualifiedHostname` in, to provide backwards compatibility.

I've also added 2 new checks:
### check-windows-logstream.ps1
A new "check if pattern exists in this file" - it although uses a StreamReader, which is much easier on memory.

It checks a file on a line-per-line basis, instead of loading a whole file into memory, and pattern matching from there. It also only checks parts that hasn't already been read.

It is inspired by [check-log.rb](https://github.com/sensu-plugins/sensu-plugins-logs/blob/master/bin/check-log.rb), which does the same.

### metric-windows-counter.ps1
This is just a generic "read a windows counter, and output in graphite format" script. It exists solely to gather Windows metrics that doesn't have a specific metric script (like `metric-cpu-load.ps1`)

### CODE REVIEW

**Comment by elfranne** [comment]
Can we get this merged @jspaleta ?

**Comment by elfranne** [comment]
why was this closed ?

**Comment by jspaleta** [comment]
Oop,
I think I closed this by accident. reopening.

**Comment by jspaleta** [comment]
@elfranne 
oh crap... this was closed because I changed the github default branch to main from master! I didnt realize it would close the pr.  

@magnuslarsen   I apologize can you re-open a new PR against the main branch?  This was collateral damage.    I'm gonna look at this pr this week.

**Pull request closed without merging**
